lib: [
  "_build/install/default/lib/ppx_wideopen/META"
  "_build/install/default/lib/ppx_wideopen/dune-package"
  "_build/install/default/lib/ppx_wideopen/opam"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.a"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.cma"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.cmi"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.cmt"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.cmx"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.cmxa"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.cmxs"
  "_build/install/default/lib/ppx_wideopen/ppx_wideopen.ml"
]
libexec: [
  "_build/install/default/lib/ppx_wideopen/ppx.exe"
]
doc: [
  "_build/install/default/doc/ppx_wideopen/README.md"
]
